"""Add user login tracking fields

Revision ID: a75d29b23287
Revises: c47484f8f97d
Create Date: 2025-08-23 12:08:55.384107

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a75d29b23287"
down_revision = "c47484f8f97d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("login_count", sa.Integer(), nullable=False))
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_column("users", "login_count")
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###
