// Mocks generated by Mockito 5.4.6 from annotations
// in cycle_avatar/test/data/services/data_export_deletion_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:cycle_avatar/data/datasources/local/database_helper.dart'
    as _i21;
import 'package:cycle_avatar/data/repositories/exercise_repository.dart'
    as _i15;
import 'package:cycle_avatar/data/repositories/notification_preferences_repository.dart'
    as _i20;
import 'package:cycle_avatar/data/repositories/notification_repository.dart'
    as _i18;
import 'package:cycle_avatar/data/repositories/pr_repository.dart' as _i16;
import 'package:cycle_avatar/data/repositories/streak_repository.dart' as _i19;
import 'package:cycle_avatar/data/repositories/template_repository.dart'
    as _i17;
import 'package:cycle_avatar/data/repositories/user_repository.dart' as _i11;
import 'package:cycle_avatar/data/repositories/workout_repository.dart' as _i13;
import 'package:cycle_avatar/domain/entities/enums.dart' as _i14;
import 'package:cycle_avatar/domain/entities/exercise.dart' as _i4;
import 'package:cycle_avatar/domain/entities/notification.dart' as _i7;
import 'package:cycle_avatar/domain/entities/notification_preferences.dart'
    as _i9;
import 'package:cycle_avatar/domain/entities/pr_record.dart' as _i5;
import 'package:cycle_avatar/domain/entities/streak_record.dart' as _i8;
import 'package:cycle_avatar/domain/entities/template.dart' as _i6;
import 'package:cycle_avatar/domain/entities/user.dart' as _i2;
import 'package:cycle_avatar/domain/entities/workout_session.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:sqflite/sqflite.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkoutSession_1 extends _i1.SmartFake
    implements _i3.WorkoutSession {
  _FakeWorkoutSession_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExercise_2 extends _i1.SmartFake implements _i4.Exercise {
  _FakeExercise_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePRRecord_3 extends _i1.SmartFake implements _i5.PRRecord {
  _FakePRRecord_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTemplate_4 extends _i1.SmartFake implements _i6.Template {
  _FakeTemplate_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotification_5 extends _i1.SmartFake implements _i7.Notification {
  _FakeNotification_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakRecord_6 extends _i1.SmartFake implements _i8.StreakRecord {
  _FakeStreakRecord_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationPreferences_7 extends _i1.SmartFake
    implements _i9.NotificationPreferences {
  _FakeNotificationPreferences_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_8 extends _i1.SmartFake implements _i10.Database {
  _FakeDatabase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i11.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.User?> findByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #findByEmail,
          [email],
        ),
        returnValue: _i12.Future<_i2.User?>.value(),
      ) as _i12.Future<_i2.User?>);

  @override
  _i12.Future<List<_i2.User>> findActiveUsers() => (super.noSuchMethod(
        Invocation.method(
          #findActiveUsers,
          [],
        ),
        returnValue: _i12.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i12.Future<List<_i2.User>>);

  @override
  _i12.Future<void> updateLastSyncTime(
    String? userId,
    DateTime? syncTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastSyncTime,
          [
            userId,
            syncTime,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updatePreferredLanguage(
    String? userId,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferredLanguage,
          [
            userId,
            language,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deactivateUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deactivateUser,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> reactivateUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #reactivateUser,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i2.User> create(_i2.User? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i2.User>);

  @override
  _i12.Future<List<_i2.User>> createBatch(List<_i2.User>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i12.Future<List<_i2.User>>);

  @override
  _i12.Future<_i2.User?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i2.User?>.value(),
      ) as _i12.Future<_i2.User?>);

  @override
  _i12.Future<List<_i2.User>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i12.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i12.Future<List<_i2.User>>);

  @override
  _i12.Future<_i2.User> update(_i2.User? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i2.User>);

  @override
  _i12.Future<List<_i2.User>> updateBatch(List<_i2.User>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i12.Future<List<_i2.User>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i2.User? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i2.User>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i12.Future<List<_i2.User>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i13.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i3.WorkoutSession>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findByUserIdAndDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findActiveSessionsByUserId(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findActiveSessionsByUserId,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findBySessionType(
          _i14.SessionType? sessionType) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBySessionType,
          [sessionType],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findUnsyncedSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #findUnsyncedSessions,
          [],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<void> markAsSynced(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [sessionId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<Map<String, dynamic>> getWorkoutStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutStats,
          [userId],
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> getRecentSessions(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSessions,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<_i3.WorkoutSession> create(_i3.WorkoutSession? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue:
            _i12.Future<_i3.WorkoutSession>.value(_FakeWorkoutSession_1(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i3.WorkoutSession>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> createBatch(
          List<_i3.WorkoutSession>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<_i3.WorkoutSession?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i3.WorkoutSession?>.value(),
      ) as _i12.Future<_i3.WorkoutSession?>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<_i3.WorkoutSession> update(_i3.WorkoutSession? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue:
            _i12.Future<_i3.WorkoutSession>.value(_FakeWorkoutSession_1(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i3.WorkoutSession>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> updateBatch(
          List<_i3.WorkoutSession>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i3.WorkoutSession? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i3.WorkoutSession>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i12.Future<List<_i3.WorkoutSession>>.value(<_i3.WorkoutSession>[]),
      ) as _i12.Future<List<_i3.WorkoutSession>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i15.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i4.Exercise>> findByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByCategory,
          [category],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<_i4.Exercise>> findByEquipment(
          _i14.EquipmentType? equipment) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByEquipment,
          [equipment],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<_i4.Exercise>> findByMuscleGroup(String? muscleGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByMuscleGroup,
          [muscleGroupId],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<_i4.Exercise>> findCompoundExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #findCompoundExercises,
          [],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<_i4.Exercise>> searchByName(
    String? query, {
    String? locale = 'en',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
          {#locale: locale},
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<_i4.Exercise>> findByTrainingGoal(_i14.TrainingGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTrainingGoal,
          [goal],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<List<Map<String, dynamic>>> getExerciseUsageStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseUsageStats,
          [],
        ),
        returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<_i4.Exercise> create(_i4.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i4.Exercise>.value(_FakeExercise_2(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i4.Exercise>);

  @override
  _i12.Future<List<_i4.Exercise>> createBatch(List<_i4.Exercise>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<_i4.Exercise?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i4.Exercise?>.value(),
      ) as _i12.Future<_i4.Exercise?>);

  @override
  _i12.Future<List<_i4.Exercise>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<_i4.Exercise> update(_i4.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i4.Exercise>.value(_FakeExercise_2(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i4.Exercise>);

  @override
  _i12.Future<List<_i4.Exercise>> updateBatch(List<_i4.Exercise>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i4.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i4.Exercise>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i4.Exercise>>.value(<_i4.Exercise>[]),
      ) as _i12.Future<List<_i4.Exercise>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [PRRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPRRepository extends _i1.Mock implements _i16.PRRepository {
  MockPRRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i5.PRRecord>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<List<_i5.PRRecord>> findByExerciseId(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByExerciseId,
          [exerciseId],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<List<_i5.PRRecord>> findByUserAndExercise(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserAndExercise,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<_i5.PRRecord?> getCurrentPR(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPR,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i12.Future<_i5.PRRecord?>.value(),
      ) as _i12.Future<_i5.PRRecord?>);

  @override
  _i12.Future<bool> isNewPR(
    String? userId,
    String? exerciseId,
    double? weight,
    int? reps,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNewPR,
          [
            userId,
            exerciseId,
            weight,
            reps,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i5.PRRecord> createFromWorkoutSet({
    required String? userId,
    required String? exerciseId,
    required double? weight,
    required int? reps,
    required DateTime? achievedAt,
    String? workoutSessionId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFromWorkoutSet,
          [],
          {
            #userId: userId,
            #exerciseId: exerciseId,
            #weight: weight,
            #reps: reps,
            #achievedAt: achievedAt,
            #workoutSessionId: workoutSessionId,
            #notes: notes,
          },
        ),
        returnValue: _i12.Future<_i5.PRRecord>.value(_FakePRRecord_3(
          this,
          Invocation.method(
            #createFromWorkoutSet,
            [],
            {
              #userId: userId,
              #exerciseId: exerciseId,
              #weight: weight,
              #reps: reps,
              #achievedAt: achievedAt,
              #workoutSessionId: workoutSessionId,
              #notes: notes,
            },
          ),
        )),
      ) as _i12.Future<_i5.PRRecord>);

  @override
  _i12.Future<List<_i5.PRRecord>> getPRHistory(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRHistory,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<List<_i5.PRRecord>> getRecentPRs(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentPRs,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<Map<String, dynamic>> getPRStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRStats,
          [userId],
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<List<_i5.PRRecord>> getPRsInDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRsInDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<_i5.PRRecord> verifyPR(String? prId) => (super.noSuchMethod(
        Invocation.method(
          #verifyPR,
          [prId],
        ),
        returnValue: _i12.Future<_i5.PRRecord>.value(_FakePRRecord_3(
          this,
          Invocation.method(
            #verifyPR,
            [prId],
          ),
        )),
      ) as _i12.Future<_i5.PRRecord>);

  @override
  _i12.Future<List<_i5.PRRecord>> getUnverifiedPRs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnverifiedPRs,
          [userId],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<_i5.PRRecord> create(_i5.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i5.PRRecord>.value(_FakePRRecord_3(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i5.PRRecord>);

  @override
  _i12.Future<List<_i5.PRRecord>> createBatch(List<_i5.PRRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<_i5.PRRecord?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i5.PRRecord?>.value(),
      ) as _i12.Future<_i5.PRRecord?>);

  @override
  _i12.Future<List<_i5.PRRecord>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<_i5.PRRecord> update(_i5.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i5.PRRecord>.value(_FakePRRecord_3(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i5.PRRecord>);

  @override
  _i12.Future<List<_i5.PRRecord>> updateBatch(List<_i5.PRRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i5.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i5.PRRecord>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i5.PRRecord>>.value(<_i5.PRRecord>[]),
      ) as _i12.Future<List<_i5.PRRecord>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [TemplateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateRepository extends _i1.Mock
    implements _i17.TemplateRepository {
  MockTemplateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i6.Template>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<List<_i6.Template>> findPublicTemplates() => (super.noSuchMethod(
        Invocation.method(
          #findPublicTemplates,
          [],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<List<_i6.Template>> findByTags(List<String>? tags) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTags,
          [tags],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<List<_i6.Template>> findByMuscleGroups(
          List<String>? muscleGroupIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByMuscleGroups,
          [muscleGroupIds],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<List<_i6.Template>> searchTemplates(
    String? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTemplates,
          [query],
          {#userId: userId},
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<List<_i6.Template>> getMostUsedTemplates(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostUsedTemplates,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<void> markAsUsed(String? templateId) => (super.noSuchMethod(
        Invocation.method(
          #markAsUsed,
          [templateId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i6.Template?> findByIdWithExercises(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIdWithExercises,
          [id],
        ),
        returnValue: _i12.Future<_i6.Template?>.value(),
      ) as _i12.Future<_i6.Template?>);

  @override
  _i12.Future<_i6.Template> create(_i6.Template? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i6.Template>.value(_FakeTemplate_4(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i6.Template>);

  @override
  _i12.Future<List<_i6.Template>> createBatch(List<_i6.Template>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<_i6.Template?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i6.Template?>.value(),
      ) as _i12.Future<_i6.Template?>);

  @override
  _i12.Future<List<_i6.Template>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<_i6.Template> update(_i6.Template? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i6.Template>.value(_FakeTemplate_4(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i6.Template>);

  @override
  _i12.Future<List<_i6.Template>> updateBatch(List<_i6.Template>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i6.Template? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i6.Template>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i6.Template>>.value(<_i6.Template>[]),
      ) as _i12.Future<List<_i6.Template>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i18.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i7.Notification>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<List<_i7.Notification>> getUnreadByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadByUserId,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<List<_i7.Notification>> getByUserIdAndType(
    String? userId,
    _i7.NotificationType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByUserIdAndType,
          [
            userId,
            type,
          ],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<List<_i7.Notification>> getReadyToSend() => (super.noSuchMethod(
        Invocation.method(
          #getReadyToSend,
          [],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<List<_i7.Notification>> getPendingScheduled() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingScheduled,
          [],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<void> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> markAsSent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSent,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> markAllAsReadForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #markAllAsReadForUser,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<int> deleteOldNotifications(int? daysOld) => (super.noSuchMethod(
        Invocation.method(
          #deleteOldNotifications,
          [daysOld],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<Map<_i7.NotificationType, int>> getNotificationCountsByType(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationCountsByType,
          [userId],
        ),
        returnValue: _i12.Future<Map<_i7.NotificationType, int>>.value(
            <_i7.NotificationType, int>{}),
      ) as _i12.Future<Map<_i7.NotificationType, int>>);

  @override
  _i12.Future<List<_i7.Notification>> getRecentNotifications(
    String? userId,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentNotifications,
          [
            userId,
            days,
          ],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<bool> hasSimilarRecentNotification(
    String? userId,
    _i7.NotificationType? type,
    Duration? withinDuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasSimilarRecentNotification,
          [
            userId,
            type,
            withinDuration,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> getUserEngagementScore(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserEngagementScore,
          [userId],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<_i7.Notification> create(_i7.Notification? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i7.Notification>.value(_FakeNotification_5(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i7.Notification>);

  @override
  _i12.Future<List<_i7.Notification>> createBatch(
          List<_i7.Notification>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<_i7.Notification?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i7.Notification?>.value(),
      ) as _i12.Future<_i7.Notification?>);

  @override
  _i12.Future<List<_i7.Notification>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<_i7.Notification> update(_i7.Notification? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i7.Notification>.value(_FakeNotification_5(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i7.Notification>);

  @override
  _i12.Future<List<_i7.Notification>> updateBatch(
          List<_i7.Notification>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i7.Notification? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i7.Notification>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i12.Future<List<_i7.Notification>>.value(<_i7.Notification>[]),
      ) as _i12.Future<List<_i7.Notification>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [StreakRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRepository extends _i1.Mock implements _i19.StreakRepository {
  MockStreakRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i8.StreakRecord>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<_i8.StreakRecord?> findByUserAndType(
    String? userId,
    _i8.StreakType? streakType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserAndType,
          [
            userId,
            streakType,
          ],
        ),
        returnValue: _i12.Future<_i8.StreakRecord?>.value(),
      ) as _i12.Future<_i8.StreakRecord?>);

  @override
  _i12.Future<List<_i8.StreakRecord>> getActiveStreaks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveStreaks,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<Map<String, dynamic>> getStreakStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakStats,
          [userId],
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<_i8.StreakRecord> updateStreakWithWorkout(
    String? userId,
    _i8.StreakType? streakType,
    DateTime? workoutDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreakWithWorkout,
          [
            userId,
            streakType,
            workoutDate,
          ],
        ),
        returnValue: _i12.Future<_i8.StreakRecord>.value(_FakeStreakRecord_6(
          this,
          Invocation.method(
            #updateStreakWithWorkout,
            [
              userId,
              streakType,
              workoutDate,
            ],
          ),
        )),
      ) as _i12.Future<_i8.StreakRecord>);

  @override
  _i12.Future<_i8.StreakRecord> breakStreak(String? streakId) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakStreak,
          [streakId],
        ),
        returnValue: _i12.Future<_i8.StreakRecord>.value(_FakeStreakRecord_6(
          this,
          Invocation.method(
            #breakStreak,
            [streakId],
          ),
        )),
      ) as _i12.Future<_i8.StreakRecord>);

  @override
  _i12.Future<List<_i8.StreakMilestone>> getRecentMilestones(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMilestones,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i12.Future<List<_i8.StreakMilestone>>.value(
            <_i8.StreakMilestone>[]),
      ) as _i12.Future<List<_i8.StreakMilestone>>);

  @override
  _i12.Future<List<_i8.StreakMilestone>> getAllMilestones(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMilestones,
          [userId],
        ),
        returnValue: _i12.Future<List<_i8.StreakMilestone>>.value(
            <_i8.StreakMilestone>[]),
      ) as _i12.Future<List<_i8.StreakMilestone>>);

  @override
  _i12.Future<List<_i8.StreakRecord>> checkAndUpdateBrokenStreaks(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndUpdateBrokenStreaks,
          [userId],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<_i8.StreakRecord> create(_i8.StreakRecord? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i8.StreakRecord>.value(_FakeStreakRecord_6(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i8.StreakRecord>);

  @override
  _i12.Future<List<_i8.StreakRecord>> createBatch(
          List<_i8.StreakRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<_i8.StreakRecord?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i8.StreakRecord?>.value(),
      ) as _i12.Future<_i8.StreakRecord?>);

  @override
  _i12.Future<List<_i8.StreakRecord>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<_i8.StreakRecord> update(_i8.StreakRecord? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i8.StreakRecord>.value(_FakeStreakRecord_6(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i8.StreakRecord>);

  @override
  _i12.Future<List<_i8.StreakRecord>> updateBatch(
          List<_i8.StreakRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i8.StreakRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i8.StreakRecord>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i12.Future<List<_i8.StreakRecord>>.value(<_i8.StreakRecord>[]),
      ) as _i12.Future<List<_i8.StreakRecord>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [NotificationPreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationPreferencesRepository extends _i1.Mock
    implements _i20.NotificationPreferencesRepository {
  MockNotificationPreferencesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i9.NotificationPreferences?> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i12.Future<_i9.NotificationPreferences?>.value(),
      ) as _i12.Future<_i9.NotificationPreferences?>);

  @override
  _i12.Future<_i9.NotificationPreferences> createDefaultForUser(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDefaultForUser,
          [userId],
        ),
        returnValue: _i12.Future<_i9.NotificationPreferences>.value(
            _FakeNotificationPreferences_7(
          this,
          Invocation.method(
            #createDefaultForUser,
            [userId],
          ),
        )),
      ) as _i12.Future<_i9.NotificationPreferences>);

  @override
  _i12.Future<void> updateNotificationTypeSetting(
    String? userId,
    String? notificationType,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationTypeSetting,
          [
            userId,
            notificationType,
            enabled,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateQuietHours(
    String? userId,
    int? startHour,
    int? startMinute,
    int? endHour,
    int? endMinute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuietHours,
          [
            userId,
            startHour,
            startMinute,
            endHour,
            endMinute,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateEnabledDays(
    String? userId,
    List<int>? enabledDays,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnabledDays,
          [
            userId,
            enabledDays,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i9.NotificationPreferences> create(
          _i9.NotificationPreferences? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i12.Future<_i9.NotificationPreferences>.value(
            _FakeNotificationPreferences_7(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i12.Future<_i9.NotificationPreferences>);

  @override
  _i12.Future<List<_i9.NotificationPreferences>> createBatch(
          List<_i9.NotificationPreferences>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i9.NotificationPreferences>>.value(
            <_i9.NotificationPreferences>[]),
      ) as _i12.Future<List<_i9.NotificationPreferences>>);

  @override
  _i12.Future<_i9.NotificationPreferences?> findById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i12.Future<_i9.NotificationPreferences?>.value(),
      ) as _i12.Future<_i9.NotificationPreferences?>);

  @override
  _i12.Future<List<_i9.NotificationPreferences>> findAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i12.Future<List<_i9.NotificationPreferences>>.value(
            <_i9.NotificationPreferences>[]),
      ) as _i12.Future<List<_i9.NotificationPreferences>>);

  @override
  _i12.Future<_i9.NotificationPreferences> update(
          _i9.NotificationPreferences? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i12.Future<_i9.NotificationPreferences>.value(
            _FakeNotificationPreferences_7(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i12.Future<_i9.NotificationPreferences>);

  @override
  _i12.Future<List<_i9.NotificationPreferences>> updateBatch(
          List<_i9.NotificationPreferences>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i12.Future<List<_i9.NotificationPreferences>>.value(
            <_i9.NotificationPreferences>[]),
      ) as _i12.Future<List<_i9.NotificationPreferences>>);

  @override
  _i12.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> delete(_i9.NotificationPreferences? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i9.NotificationPreferences>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i9.NotificationPreferences>>.value(
            <_i9.NotificationPreferences>[]),
      ) as _i12.Future<List<_i9.NotificationPreferences>>);

  @override
  _i12.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i21.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i10.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i12.Future<_i10.Database>.value(_FakeDatabase_8(
          this,
          Invocation.getter(#database),
        )),
      ) as _i12.Future<_i10.Database>);

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<int> getDatabaseSize() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSize,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<void> vacuum() => (super.noSuchMethod(
        Invocation.method(
          #vacuum,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<bool> checkIntegrity() => (super.noSuchMethod(
        Invocation.method(
          #checkIntegrity,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<Map<String, dynamic>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue:
            _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<List<Map<String, dynamic>>> getMigrationHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMigrationHistory,
          [],
        ),
        returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i12.Future<List<Map<String, dynamic>>>);

  @override
  _i12.Future<String?> backupDatabase() => (super.noSuchMethod(
        Invocation.method(
          #backupDatabase,
          [],
        ),
        returnValue: _i12.Future<String?>.value(),
      ) as _i12.Future<String?>);

  @override
  _i12.Future<bool> restoreDatabase(String? backupPath) => (super.noSuchMethod(
        Invocation.method(
          #restoreDatabase,
          [backupPath],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> changeEncryptionKey(String? newKey) => (super.noSuchMethod(
        Invocation.method(
          #changeEncryptionKey,
          [newKey],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #removeEncryptionKey,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<String> exportSchema() => (super.noSuchMethod(
        Invocation.method(
          #exportSchema,
          [],
        ),
        returnValue: _i12.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #exportSchema,
            [],
          ),
        )),
      ) as _i12.Future<String>);
}
