// Mocks generated by Mockito 5.4.6 from annotations
// in cycle_avatar/test/domain/services/pr_tracking_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cycle_avatar/data/repositories/exercise_repository.dart' as _i6;
import 'package:cycle_avatar/data/repositories/pr_repository.dart' as _i4;
import 'package:cycle_avatar/domain/entities/enums.dart' as _i7;
import 'package:cycle_avatar/domain/entities/exercise.dart' as _i3;
import 'package:cycle_avatar/domain/entities/pr_record.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePRRecord_0 extends _i1.SmartFake implements _i2.PRRecord {
  _FakePRRecord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PRRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPRRepository extends _i1.Mock implements _i4.PRRepository {
  MockPRRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.PRRecord>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<List<_i2.PRRecord>> findByExerciseId(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByExerciseId,
          [exerciseId],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<List<_i2.PRRecord>> findByUserAndExercise(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserAndExercise,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<_i2.PRRecord?> getCurrentPR(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPR,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<_i2.PRRecord?>.value(),
      ) as _i5.Future<_i2.PRRecord?>);

  @override
  _i5.Future<bool> isNewPR(
    String? userId,
    String? exerciseId,
    double? weight,
    int? reps,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNewPR,
          [
            userId,
            exerciseId,
            weight,
            reps,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.PRRecord> createFromWorkoutSet({
    required String? userId,
    required String? exerciseId,
    required double? weight,
    required int? reps,
    required DateTime? achievedAt,
    String? workoutSessionId,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFromWorkoutSet,
          [],
          {
            #userId: userId,
            #exerciseId: exerciseId,
            #weight: weight,
            #reps: reps,
            #achievedAt: achievedAt,
            #workoutSessionId: workoutSessionId,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<_i2.PRRecord>.value(_FakePRRecord_0(
          this,
          Invocation.method(
            #createFromWorkoutSet,
            [],
            {
              #userId: userId,
              #exerciseId: exerciseId,
              #weight: weight,
              #reps: reps,
              #achievedAt: achievedAt,
              #workoutSessionId: workoutSessionId,
              #notes: notes,
            },
          ),
        )),
      ) as _i5.Future<_i2.PRRecord>);

  @override
  _i5.Future<List<_i2.PRRecord>> getPRHistory(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRHistory,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<List<_i2.PRRecord>> getRecentPRs(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentPRs,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<Map<String, dynamic>> getPRStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRStats,
          [userId],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i2.PRRecord>> getPRsInDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRsInDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<_i2.PRRecord> verifyPR(String? prId) => (super.noSuchMethod(
        Invocation.method(
          #verifyPR,
          [prId],
        ),
        returnValue: _i5.Future<_i2.PRRecord>.value(_FakePRRecord_0(
          this,
          Invocation.method(
            #verifyPR,
            [prId],
          ),
        )),
      ) as _i5.Future<_i2.PRRecord>);

  @override
  _i5.Future<List<_i2.PRRecord>> getUnverifiedPRs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnverifiedPRs,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<_i2.PRRecord> create(_i2.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i5.Future<_i2.PRRecord>.value(_FakePRRecord_0(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i5.Future<_i2.PRRecord>);

  @override
  _i5.Future<List<_i2.PRRecord>> createBatch(List<_i2.PRRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<_i2.PRRecord?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i5.Future<_i2.PRRecord?>.value(),
      ) as _i5.Future<_i2.PRRecord?>);

  @override
  _i5.Future<List<_i2.PRRecord>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<_i2.PRRecord> update(_i2.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i5.Future<_i2.PRRecord>.value(_FakePRRecord_0(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i5.Future<_i2.PRRecord>);

  @override
  _i5.Future<List<_i2.PRRecord>> updateBatch(List<_i2.PRRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> delete(_i2.PRRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.PRRecord>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i2.PRRecord>>.value(<_i2.PRRecord>[]),
      ) as _i5.Future<List<_i2.PRRecord>>);

  @override
  _i5.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i6.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Exercise>> findByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<_i3.Exercise>> findByEquipment(
          _i7.EquipmentType? equipment) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByEquipment,
          [equipment],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<_i3.Exercise>> findByMuscleGroup(String? muscleGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByMuscleGroup,
          [muscleGroupId],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<_i3.Exercise>> findCompoundExercises() => (super.noSuchMethod(
        Invocation.method(
          #findCompoundExercises,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<_i3.Exercise>> searchByName(
    String? query, {
    String? locale = 'en',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
          {#locale: locale},
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<_i3.Exercise>> findByTrainingGoal(_i7.TrainingGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByTrainingGoal,
          [goal],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getExerciseUsageStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseUsageStats,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.Exercise> create(_i3.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i5.Future<_i3.Exercise>.value(_FakeExercise_1(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i5.Future<_i3.Exercise>);

  @override
  _i5.Future<List<_i3.Exercise>> createBatch(List<_i3.Exercise>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<_i3.Exercise?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Exercise?>.value(),
      ) as _i5.Future<_i3.Exercise?>);

  @override
  _i5.Future<List<_i3.Exercise>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<_i3.Exercise> update(_i3.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i5.Future<_i3.Exercise>.value(_FakeExercise_1(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i5.Future<_i3.Exercise>);

  @override
  _i5.Future<List<_i3.Exercise>> updateBatch(List<_i3.Exercise>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> delete(_i3.Exercise? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Exercise>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
      ) as _i5.Future<List<_i3.Exercise>>);

  @override
  _i5.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
