// Mocks generated by Mockito 5.4.6 from annotations
// in cycle_avatar/test/domain/services/streak_tracking_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cycle_avatar/data/repositories/streak_repository.dart' as _i3;
import 'package:cycle_avatar/domain/entities/streak_record.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreakRecord_0 extends _i1.SmartFake implements _i2.StreakRecord {
  _FakeStreakRecord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StreakRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRepository extends _i1.Mock implements _i3.StreakRepository {
  MockStreakRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.StreakRecord>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<_i2.StreakRecord?> findByUserAndType(
    String? userId,
    _i2.StreakType? streakType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserAndType,
          [
            userId,
            streakType,
          ],
        ),
        returnValue: _i4.Future<_i2.StreakRecord?>.value(),
      ) as _i4.Future<_i2.StreakRecord?>);

  @override
  _i4.Future<List<_i2.StreakRecord>> getActiveStreaks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveStreaks,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<Map<String, dynamic>> getStreakStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakStats,
          [userId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.StreakRecord> updateStreakWithWorkout(
    String? userId,
    _i2.StreakType? streakType,
    DateTime? workoutDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreakWithWorkout,
          [
            userId,
            streakType,
            workoutDate,
          ],
        ),
        returnValue: _i4.Future<_i2.StreakRecord>.value(_FakeStreakRecord_0(
          this,
          Invocation.method(
            #updateStreakWithWorkout,
            [
              userId,
              streakType,
              workoutDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.StreakRecord>);

  @override
  _i4.Future<_i2.StreakRecord> breakStreak(String? streakId) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakStreak,
          [streakId],
        ),
        returnValue: _i4.Future<_i2.StreakRecord>.value(_FakeStreakRecord_0(
          this,
          Invocation.method(
            #breakStreak,
            [streakId],
          ),
        )),
      ) as _i4.Future<_i2.StreakRecord>);

  @override
  _i4.Future<List<_i2.StreakMilestone>> getRecentMilestones(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMilestones,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.StreakMilestone>>.value(
            <_i2.StreakMilestone>[]),
      ) as _i4.Future<List<_i2.StreakMilestone>>);

  @override
  _i4.Future<List<_i2.StreakMilestone>> getAllMilestones(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMilestones,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.StreakMilestone>>.value(
            <_i2.StreakMilestone>[]),
      ) as _i4.Future<List<_i2.StreakMilestone>>);

  @override
  _i4.Future<List<_i2.StreakRecord>> checkAndUpdateBrokenStreaks(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndUpdateBrokenStreaks,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<_i2.StreakRecord> create(_i2.StreakRecord? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i4.Future<_i2.StreakRecord>.value(_FakeStreakRecord_0(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i4.Future<_i2.StreakRecord>);

  @override
  _i4.Future<List<_i2.StreakRecord>> createBatch(
          List<_i2.StreakRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<_i2.StreakRecord?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i4.Future<_i2.StreakRecord?>.value(),
      ) as _i4.Future<_i2.StreakRecord?>);

  @override
  _i4.Future<List<_i2.StreakRecord>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<_i2.StreakRecord> update(_i2.StreakRecord? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i4.Future<_i2.StreakRecord>.value(_FakeStreakRecord_0(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i4.Future<_i2.StreakRecord>);

  @override
  _i4.Future<List<_i2.StreakRecord>> updateBatch(
          List<_i2.StreakRecord>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> delete(_i2.StreakRecord? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.StreakRecord>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.StreakRecord>>.value(<_i2.StreakRecord>[]),
      ) as _i4.Future<List<_i2.StreakRecord>>);

  @override
  _i4.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
