// Mocks generated by Mockito 5.4.6 from annotations
// in cycle_avatar/test/domain/services/weekly_highlight_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cycle_avatar/data/repositories/workout_repository.dart' as _i5;
import 'package:cycle_avatar/domain/entities/enums.dart' as _i7;
import 'package:cycle_avatar/domain/entities/pr_record.dart' as _i3;
import 'package:cycle_avatar/domain/entities/streak_record.dart' as _i4;
import 'package:cycle_avatar/domain/entities/workout_session.dart' as _i2;
import 'package:cycle_avatar/domain/services/pr_tracking_service.dart' as _i8;
import 'package:cycle_avatar/domain/services/streak_tracking_service.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutSession_0 extends _i1.SmartFake
    implements _i2.WorkoutSession {
  _FakeWorkoutSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePRRecord_1 extends _i1.SmartFake implements _i3.PRRecord {
  _FakePRRecord_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakRecord_2 extends _i1.SmartFake implements _i4.StreakRecord {
  _FakeStreakRecord_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i5.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.WorkoutSession>> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findByUserIdAndDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findActiveSessionsByUserId(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findActiveSessionsByUserId,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findBySessionType(
          _i7.SessionType? sessionType) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBySessionType,
          [sessionType],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findUnsyncedSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #findUnsyncedSessions,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<void> markAsSynced(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [sessionId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getWorkoutStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutStats,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> getRecentSessions(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSessions,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<_i2.WorkoutSession> create(_i2.WorkoutSession? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [entity],
        ),
        returnValue: _i6.Future<_i2.WorkoutSession>.value(_FakeWorkoutSession_0(
          this,
          Invocation.method(
            #create,
            [entity],
          ),
        )),
      ) as _i6.Future<_i2.WorkoutSession>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> createBatch(
          List<_i2.WorkoutSession>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBatch,
          [entities],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<_i2.WorkoutSession?> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i6.Future<_i2.WorkoutSession?>.value(),
      ) as _i6.Future<_i2.WorkoutSession?>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<_i2.WorkoutSession> update(_i2.WorkoutSession? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i6.Future<_i2.WorkoutSession>.value(_FakeWorkoutSession_0(
          this,
          Invocation.method(
            #update,
            [entity],
          ),
        )),
      ) as _i6.Future<_i2.WorkoutSession>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> updateBatch(
          List<_i2.WorkoutSession>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [entities],
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<bool> deleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> delete(_i2.WorkoutSession? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> exists(String? id) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i2.WorkoutSession>> findWithPagination({
    int? offset = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithPagination,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<List<_i2.WorkoutSession>>.value(<_i2.WorkoutSession>[]),
      ) as _i6.Future<List<_i2.WorkoutSession>>);

  @override
  _i6.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}

/// A class which mocks [PRTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPRTrackingService extends _i1.Mock implements _i8.PRTrackingService {
  MockPRTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.PRRecord?> checkAndCreatePR({
    required String? userId,
    required _i2.WorkoutSet? workoutSet,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAndCreatePR,
          [],
          {
            #userId: userId,
            #workoutSet: workoutSet,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<_i3.PRRecord?>.value(),
      ) as _i6.Future<_i3.PRRecord?>);

  @override
  _i6.Future<List<_i3.PRRecord>> processWorkoutSessionForPRs({
    required String? userId,
    required _i2.WorkoutSession? session,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processWorkoutSessionForPRs,
          [],
          {
            #userId: userId,
            #session: session,
          },
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<List<_i3.PRRecord>> getCurrentPRs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPRs,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<List<_i3.PRRecord>> getPRHistory(
    String? userId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRHistory,
          [
            userId,
            exerciseId,
          ],
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<List<_i3.PRRecord>> getRecentPRs(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentPRs,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<Map<String, dynamic>> getPRStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRStats,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i3.PRRecord>> getPRsInDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRsInDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<_i3.PRRecord> verifyPR(String? prId) => (super.noSuchMethod(
        Invocation.method(
          #verifyPR,
          [prId],
        ),
        returnValue: _i6.Future<_i3.PRRecord>.value(_FakePRRecord_1(
          this,
          Invocation.method(
            #verifyPR,
            [prId],
          ),
        )),
      ) as _i6.Future<_i3.PRRecord>);

  @override
  _i6.Future<List<_i3.PRRecord>> getUnverifiedPRs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnverifiedPRs,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.PRRecord>>.value(<_i3.PRRecord>[]),
      ) as _i6.Future<List<_i3.PRRecord>>);

  @override
  _i6.Future<double> calculatePRImprovement(
    String? userId,
    String? exerciseId,
    Duration? timeframe,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePRImprovement,
          [
            userId,
            exerciseId,
            timeframe,
          ],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<Map<String, dynamic>> getPRCelebrationData(_i3.PRRecord? pr) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPRCelebrationData,
          [pr],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [StreakTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakTrackingService extends _i1.Mock
    implements _i9.StreakTrackingService {
  MockStreakTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.StreakRecord>> updateStreaksWithWorkout({
    required String? userId,
    required _i2.WorkoutSession? session,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreaksWithWorkout,
          [],
          {
            #userId: userId,
            #session: session,
          },
        ),
        returnValue:
            _i6.Future<List<_i4.StreakRecord>>.value(<_i4.StreakRecord>[]),
      ) as _i6.Future<List<_i4.StreakRecord>>);

  @override
  _i6.Future<List<_i4.StreakRecord>> getActiveStreaks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveStreaks,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i4.StreakRecord>>.value(<_i4.StreakRecord>[]),
      ) as _i6.Future<List<_i4.StreakRecord>>);

  @override
  _i6.Future<Map<String, dynamic>> getStreakStats(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakStats,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.StreakRecord?> getStreakByType(
    String? userId,
    _i4.StreakType? streakType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakByType,
          [
            userId,
            streakType,
          ],
        ),
        returnValue: _i6.Future<_i4.StreakRecord?>.value(),
      ) as _i6.Future<_i4.StreakRecord?>);

  @override
  _i6.Future<List<_i4.StreakMilestone>> getRecentMilestones(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMilestones,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i4.StreakMilestone>>.value(
            <_i4.StreakMilestone>[]),
      ) as _i6.Future<List<_i4.StreakMilestone>>);

  @override
  _i6.Future<List<_i4.StreakMilestone>> getAllMilestones(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMilestones,
          [userId],
        ),
        returnValue: _i6.Future<List<_i4.StreakMilestone>>.value(
            <_i4.StreakMilestone>[]),
      ) as _i6.Future<List<_i4.StreakMilestone>>);

  @override
  _i6.Future<List<_i4.StreakMilestone>> checkForNewMilestones(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForNewMilestones,
          [userId],
        ),
        returnValue: _i6.Future<List<_i4.StreakMilestone>>.value(
            <_i4.StreakMilestone>[]),
      ) as _i6.Future<List<_i4.StreakMilestone>>);

  @override
  _i6.Future<Map<String, dynamic>> getStreakMotivationData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakMotivationData,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.StreakRecord> breakStreak(String? streakId) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakStreak,
          [streakId],
        ),
        returnValue: _i6.Future<_i4.StreakRecord>.value(_FakeStreakRecord_2(
          this,
          Invocation.method(
            #breakStreak,
            [streakId],
          ),
        )),
      ) as _i6.Future<_i4.StreakRecord>);

  @override
  _i6.Future<Map<String, dynamic>> getStreakVisualizationData(
    String? userId,
    _i4.StreakType? streakType, {
    int? days = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakVisualizationData,
          [
            userId,
            streakType,
          ],
          {#days: days},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}
