// Mocks generated by Mockito 5.4.6 from annotations
// in cycle_avatar/test/integration/sync_functionality_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cycle_avatar/data/datasources/local/background_sync_service.dart'
    as _i2;
import 'package:cycle_avatar/data/datasources/local/conflict_resolver.dart'
    as _i4;
import 'package:cycle_avatar/data/datasources/local/sync_manager.dart' as _i9;
import 'package:cycle_avatar/data/services/sync_service.dart' as _i5;
import 'package:cycle_avatar/domain/entities/sync_entity.dart' as _i3;
import 'package:cycle_avatar/domain/entities/user.dart' as _i8;
import 'package:cycle_avatar/domain/entities/workout_session.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkStatus_0 extends _i1.SmartFake implements _i2.NetworkStatus {
  _FakeNetworkStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncProgress_1 extends _i1.SmartFake implements _i2.SyncProgress {
  _FakeSyncProgress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_2 extends _i1.SmartFake implements _i3.SyncResult {
  _FakeSyncResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConflictResolutionResult_3 extends _i1.SmartFake
    implements _i4.ConflictResolutionResult {
  _FakeConflictResolutionResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i5.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.SyncResult> get syncResults => (super.noSuchMethod(
        Invocation.getter(#syncResults),
        returnValue: _i6.Stream<_i3.SyncResult>.empty(),
      ) as _i6.Stream<_i3.SyncResult>);

  @override
  _i6.Stream<_i3.SyncStatus> get syncStatus => (super.noSuchMethod(
        Invocation.getter(#syncStatus),
        returnValue: _i6.Stream<_i3.SyncStatus>.empty(),
      ) as _i6.Stream<_i3.SyncStatus>);

  @override
  _i6.Stream<_i2.BackgroundSyncStatus> get backgroundSyncStatus =>
      (super.noSuchMethod(
        Invocation.getter(#backgroundSyncStatus),
        returnValue: _i6.Stream<_i2.BackgroundSyncStatus>.empty(),
      ) as _i6.Stream<_i2.BackgroundSyncStatus>);

  @override
  _i6.Stream<_i2.NetworkStatus> get networkStatus => (super.noSuchMethod(
        Invocation.getter(#networkStatus),
        returnValue: _i6.Stream<_i2.NetworkStatus>.empty(),
      ) as _i6.Stream<_i2.NetworkStatus>);

  @override
  _i6.Stream<_i3.SyncConflict> get conflicts => (super.noSuchMethod(
        Invocation.getter(#conflicts),
        returnValue: _i6.Stream<_i3.SyncConflict>.empty(),
      ) as _i6.Stream<_i3.SyncConflict>);

  @override
  _i3.SyncStatus get currentSyncStatus => (super.noSuchMethod(
        Invocation.getter(#currentSyncStatus),
        returnValue: _i3.SyncStatus.pending,
      ) as _i3.SyncStatus);

  @override
  _i2.NetworkStatus get currentNetworkStatus => (super.noSuchMethod(
        Invocation.getter(#currentNetworkStatus),
        returnValue: _FakeNetworkStatus_0(
          this,
          Invocation.getter(#currentNetworkStatus),
        ),
      ) as _i2.NetworkStatus);

  @override
  bool get isBackgroundSyncEnabled => (super.noSuchMethod(
        Invocation.getter(#isBackgroundSyncEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncWorkoutSession(_i7.WorkoutSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWorkoutSession,
          [session],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncWorkoutSets(List<_i7.WorkoutSet>? sets) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWorkoutSets,
          [sets],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncUser(_i8.User? user) => (super.noSuchMethod(
        Invocation.method(
          #syncUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncDeletion({
    required _i3.SyncEntityType? entityType,
    required String? entityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncDeletion,
          [],
          {
            #entityType: entityType,
            #entityId: entityId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> triggerSync() => (super.noSuchMethod(
        Invocation.method(
          #triggerSync,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setBackgroundSyncEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setBackgroundSyncEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.SyncProgress> getSyncProgress() => (super.noSuchMethod(
        Invocation.method(
          #getSyncProgress,
          [],
        ),
        returnValue: _i6.Future<_i2.SyncProgress>.value(_FakeSyncProgress_1(
          this,
          Invocation.method(
            #getSyncProgress,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SyncProgress>);

  @override
  _i6.Future<Map<String, dynamic>> getSyncStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStatistics,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> clearCompletedSyncEntities() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedSyncEntities,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllSyncEntities() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSyncEntities,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncCompleteWorkout({
    required _i7.WorkoutSession? session,
    required List<_i7.WorkoutSet>? sets,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncCompleteWorkout,
          [],
          {
            #session: session,
            #sets: sets,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncUserProfile(_i8.User? user) => (super.noSuchMethod(
        Invocation.method(
          #syncUserProfile,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncTemplate(Map<String, dynamic>? templateData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTemplate,
          [templateData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncPRRecord(Map<String, dynamic>? prData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncPRRecord,
          [prData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncAvatarState(Map<String, dynamic>? avatarData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAvatarState,
          [avatarData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncRecoveryState(Map<String, dynamic>? recoveryData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncRecoveryState,
          [recoveryData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncFatigueEvent(Map<String, dynamic>? fatigueData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncFatigueEvent,
          [fatigueData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getPendingSyncCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getFailedSyncCount() => (super.noSuchMethod(
        Invocation.method(
          #getFailedSyncCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i3.SyncResult> forceSyncForTesting() => (super.noSuchMethod(
        Invocation.method(
          #forceSyncForTesting,
          [],
        ),
        returnValue: _i6.Future<_i3.SyncResult>.value(_FakeSyncResult_2(
          this,
          Invocation.method(
            #forceSyncForTesting,
            [],
          ),
        )),
      ) as _i6.Future<_i3.SyncResult>);
}

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i9.SyncManager {
  MockSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.SyncResult> get syncResults => (super.noSuchMethod(
        Invocation.getter(#syncResults),
        returnValue: _i6.Stream<_i3.SyncResult>.empty(),
      ) as _i6.Stream<_i3.SyncResult>);

  @override
  _i6.Stream<_i3.SyncStatus> get syncStatus => (super.noSuchMethod(
        Invocation.getter(#syncStatus),
        returnValue: _i6.Stream<_i3.SyncStatus>.empty(),
      ) as _i6.Stream<_i3.SyncStatus>);

  @override
  _i3.SyncStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i3.SyncStatus.pending,
      ) as _i3.SyncStatus);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> queueForSync(_i3.SyncEntity? syncEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueForSync,
          [syncEntity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> queueBatchForSync(List<_i3.SyncEntity>? syncEntities) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueBatchForSync,
          [syncEntities],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.SyncResult> performSync({bool? forceSync = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performSync,
          [],
          {#forceSync: forceSync},
        ),
        returnValue: _i6.Future<_i3.SyncResult>.value(_FakeSyncResult_2(
          this,
          Invocation.method(
            #performSync,
            [],
            {#forceSync: forceSync},
          ),
        )),
      ) as _i6.Future<_i3.SyncResult>);

  @override
  _i6.Future<int> getPendingSyncCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getFailedSyncCount() => (super.noSuchMethod(
        Invocation.method(
          #getFailedSyncCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> clearCompletedSyncEntities() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedSyncEntities,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllSyncEntities() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSyncEntities,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getSyncStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStatistics,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [ConflictResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockConflictResolver extends _i1.Mock implements _i4.ConflictResolver {
  MockConflictResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.SyncConflict> get conflicts => (super.noSuchMethod(
        Invocation.getter(#conflicts),
        returnValue: _i6.Stream<_i3.SyncConflict>.empty(),
      ) as _i6.Stream<_i3.SyncConflict>);

  @override
  _i6.Future<_i4.ConflictResolutionResult> resolveConflicts({
    required _i3.SyncEntity? syncEntity,
    required Map<String, dynamic>? serverData,
    _i3.ConflictResolution? strategy = _i3.ConflictResolution.clientWins,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflicts,
          [],
          {
            #syncEntity: syncEntity,
            #serverData: serverData,
            #strategy: strategy,
          },
        ),
        returnValue: _i6.Future<_i4.ConflictResolutionResult>.value(
            _FakeConflictResolutionResult_3(
          this,
          Invocation.method(
            #resolveConflicts,
            [],
            {
              #syncEntity: syncEntity,
              #serverData: serverData,
              #strategy: strategy,
            },
          ),
        )),
      ) as _i6.Future<_i4.ConflictResolutionResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
